server:
  port: 9999
  servlet:
    context-path: /activiti

spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1lhuc84b513m4e2jo.mysql.rds.aliyuncs.com:3306/activiti_test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: activiti
      password: plm@@666
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validationQueryTimeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: log4j2
      filter:
        stat: null
        enable: true
        log-slow-sql: true
        slow-sql-millis: 1000

  activiti:
    check-process-definitions: false
    #建表规则
    #flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。
    #true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。
    #create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。
    #drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true

logging:
  level:
    # 打印mybatis的sql日志
    com:
      len:
        mapper: DEBUG
    # 打印activiti的sql日志
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity=trace:

